export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";
export const FETCH_ARTICLES_RESET = "FETCH_ARTICLES_RESET";

export const FETCH_CREATE_ARTICLES_REQUEST = "FETCH_CREATE_ARTICLES_REQUEST";
export const FETCH_CREATE_ARTICLES_SUCCESS = "FETCH_CREATE_ARTICLES_SUCCESS";
export const FETCH_CREATE_ARTICLES_FAILURE = "FETCH_CREATE_ARTICLES_FAILURE";
export const FETCH_CREATE_ARTICLES_RESET = "FETCH_CREATE_ARTICLES_RESET";

export const FETCH_EDIT_ARTICLES_REQUEST = "FETCH_EDIT_ARTICLES_REQUEST";
export const FETCH_EDIT_ARTICLES_SUCCESS = "FETCH_EDIT_ARTICLES_SUCCESS";
export const FETCH_EDIT_ARTICLES_FAILURE = "FETCH_EDIT_ARTICLES_FAILURE";
export const FETCH_EDIT_ARTICLES_RESET = "FETCH_EDIT_ARTICLES_RESET";